# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PodDemo1' do

end

target 'PodDemo1Tests' do

end

target 'PodDemo1UITests' do

end

